[package]
name = "spirinvladimir/wat-forex-calc"
version = "1.0.2"
description = "Set usefull functions for trading"
readme = "README.md"
repository = "https://github.com/spirinvladimir/wat-forex-calc"
homepage = "http://spirintravels.com/wat-forex-calc/price-for-amount"
license = "ISC"

[[module]]
name = "wat-forex-calc"
source = "main.wasm"

[[command]]
name = "wat-forex-calc"
module = "wat-forex-calc"
